import { Book } from '@/app/types/book';

export const initialBooks: Book[] = [
  {
    id: '1',
    title: 'Dom Casmurro',
    author: 'Machado de Assis',
    genre: 'Literatura Brasileira',
    pages: 256,
    rating: 5,
    synopsis: 'A história de Bento Santiago...',
    coverUrl: '/covers/dom-casmurro.jpg',
    status: 'finished',
    createdAt: new Date('2023-01-15T00:00:00'),
  },
  {
    id: '2',
    title: '1984',
    author: 'George Orwell',
    genre: 'Ficção Científica',
    pages: 328,
    rating: 4,
    synopsis: 'Um romance distópico...',
    coverUrl: '/covers/1984.jpg',
    status: 'reading',
    createdAt: new Date('2023-02-20T00:00:00'),
  },
  {
    id: '3',
    title: 'O Alquimista',
    author: 'Paulo Coelho',
    genre: 'Ficção',
    pages: 208,
    rating: 4,
    synopsis: 'A jornada de Santiago pelo deserto...',
    coverUrl: '/covers/o-alquimista.jpg',
    status: 'to-read',
    createdAt: new Date('2023-03-25T00:00:00'),
  },
  {
    id: '4',
    title: 'Harry Potter e a Pedra Filosofal',
    author: 'J.K. Rowling',
    genre: 'Fantasia',
    pages: 223,
    rating: 5,
    synopsis: 'O início das aventuras de Harry Potter...',
    coverUrl: '/covers/harry-potter.jpg',
    status: 'reading',
    createdAt: new Date('2023-04-10T00:00:00'),
  },
  {
    id: '5',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    genre: 'História',
    pages: 498,
    rating: 5,
    synopsis: 'Uma breve história da humanidade...',
    coverUrl: '/covers/sapiens.jpg',
    status: 'finished',
    createdAt: new Date('2023-05-05T00:00:00'),
  },
];
